### ISSUE TITLE
Add Description and GitHub topics to repo for discoverability

### ISSUE THREAD

**Issue by david-poindexter** [davidjrh/dnn.tls12#1]
Currently, this solution is a little known "secret".  😉  

Would you mind adding a **Description** to this repo that contains "DNN (formerly DotNetNuke)"?  

You could improve GitHub search by adding the same key phrase to the README file.  I'll be happy to create a PR for that part.

Also, it would improve GitHub search to add the minimum topics: **dnncms**, **dnn** and **dotnetnuke**.  

Thanks!

**Comment by davidjrh** [comment]
I have merged the pull request and added the tags and changed description as suggested. 

Thanks!

**Comment by david-poindexter** [comment]
Woo hoo, this repo is now discoverable in nvQuickPulse (available on Apple and Android app stores)!  :)

![d6f223c9-b20e-4932-8606-b300fd160b67](https://user-images.githubusercontent.com/4568451/52573474-3ec0dc00-2de8-11e9-91d0-68824ca3f821.png)

**Comment by davidjrh** [comment]
Omg...I hadn't noticed the visibility issue of this on my OTHER MORE INTERESTING repos, like the Azure AD module, Redis or the Application Insights ones. Going to add those descriptions on them as well.
